config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :homeworks, only: %i[index show] do
  resources :homework_users, only: %i[create destroy]
  end
  

  root 'homeworks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/homework.rb
class Homework < ApplicationRecord
    has_many :homework_users, dependent: :destroy
    has_many :users, through: :homework_users
end

app/models/homework_user.rb
class HomeworkUser < ApplicationRecord
  belongs_to :homework
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :homeworks_users, dependent: :destroy
         has_many :homeworks, through: :homework_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: :index
end

app/controllers/homework_users_controller.rb
class HomeworkUsersController < ApplicationController
    def create 
        @homework_user = HomeworkUser.new(
            user: current_user,
            homework_id: params[:homework_id]
        )
        @homework_user.completed = true
        @homework_user.save
        redirect_to homeworks_path
    end 
    def destroy
        @homework_user = HomeworkUser.where(homework_id: params[:homework_id], user: current_user)
        @homework_user.destroy_all
        @homework_user.each { |h| h.completed = false}
        
        redirect_to root_path
    end 



end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController


    def index 
        @homeworks = Homework.all
       
    end 

    def show 
        @homework = Homework.find(params[:id])
        @userscompleted = @homework.homework_users.where(completed: true)
     end 

    
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homework_users_helper.rb
module HomeworkUsersHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/homeworks/index.html.erb
<div class='row'>
<% @homeworks.each do |h| %>

    <div class="card col-sm-3" style="width: 18rem;">        
            <%= image_tag h.image, size: '200x200'%>
            <div class="card-body">
                <h5 class="card-title"><%=h.name %></h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <%=link_to 'Detalle', homework_path(h), class:"btn btn-primary" %>                        
                <%= link_to 'Completado!!', homework_homework_users_path(h), method: :post, class:"btn btn-primary" %>
                <%= link_to 'No completado', homework_homework_user_path(h, :id), method: :delete, class:"btn btn-primary" %>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/homeworks/show.html.erb
<table class='table'>
    <thead>
        <tr>
            <th><%= @homework.name %> </th>
        </tr>
        <tr>
            <th>Email de usuarios con la tarea completada</th>
        </tr>
    </thead>
    <tbody>
        <% @userscompleted.each do |u| %>
        <tr>
            <td><%= u.user.email %></td>
        </tr>
        <% end %>
    </tbody>
</table>






<%= link_to 'Back', root_path, class:"btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">            
            <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete,class:'nav-link' %>        
              </li>
            
              <%else%>   
              <li class="nav-item">
                  <%= link_to 'Iniciar sesión', new_user_session_path, class:'nav-link' %>       
              </li>  
              <li class="nav-item">
                  <%= link_to 'Registrarse', new_user_registration_path, class:'nav-link' %>       
              </li>  
            <% end %>     
            </ul>            
          </div>
      </nav>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>


    <div class='container'>
    <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>